pmOnFail: ignore

minimumReleaseAgeExclude:
  - '@azohra/meteo.briefing'
  - '@azohra/meteo.core'
  - '@azohra/meteo.forecast'
  - '@azohra/meteo.grib'
  - '@azohra/meteo.j2k'
  - '@azohra/meteo.station'
